name: CI- Build and push the Docker Image

on:
  push:
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-latest


    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run:  |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/fastapi-demo:${{ github.sha }} .

      - name: Push Docker Image to DockerHub
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/fastapi-demo:${{ github.sha }}


      - name: Set image tag as output for CD pipeline
        id: image
        run: echo "image_tag=${{ github.sha }}" >> $GITHUB_OUTPUT
         

